// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.40.5'
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.5.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    core_version = '1.8.0'
    appcompat_version = '1.4.2'
    material_version = '1.6.1'
    constraint_version = '2.1.4'
    coroutines_version = '1.5.0'
    firestore_version = '24.2.1'
    firestorage_version = '20.0.1'
    firebaseauth_version = '21.0.6'
    firebase_crashlytics_version = '18.2.11'
    firebase_analytics_version = '21.1.0'
    firebase_coroutines_version = '1.5.0'
    fragment_version = '1.5.0'
    lifecycle_version = '2.5.0'
    nav_version = '2.5.1'
    worker_version = '2.7.1'
    jodatime_version = '2.10.12.2'
    hilt_version = '2.40.5'
    picasso_version = '2.71828'
    compressor_version = '3.0.1'
    progress_button_version = '2.1.0'
}